name: DJDionysosV1
favicon: null
layout_spectrum: 0.95971
typography_spectrum: 0.346378106623888
title: 'DJ Dionysos The Incredible '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#88393f'
    - '#b8a797'
    - '#f8f5ee'
    - '#5d674c'
  brandStrength: 0.125
  lightness: 0.9325035915244371
  saturation: 0.373453859006986
  rhythmicContrast: 0.9690901129506528
purpose: []
